[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
betezen = "coUnmi3oBUtwtd9fjeAvSsJssXh5A5xyPbhpewyzRVF"

[programs.devnet]
betezen = "49BKpDeZKKAGt6cRn5fGb3DizL64XSyHpbta3xdbSEKq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 test/*.ts"
